### ISSUE TITLE
`Denite history:search` error

### ISSUE THREAD

**Issue by sodiumjoe** [neoclide/denite-extra#3]
minimal vimrc:
```vimL
call plug#begin('~/.vim/plugged')
Plug 'chemzqm/denite-extra'
Plug 'Shougo/denite.nvim'
call plug#end()
```

repro:
```bash
$ nvim
```
```
:Denite history:search
```

on `<enter>` I get:

```[denite] Traceback (most recent call last):
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 119, in start
[denite]     status = self._prompt.start()
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 182, in start
[denite]     raise e
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/prompt/prompt.py", line 172, in start
[denite]     callback=self.on_harvest,
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/prompt.py", line 98, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/action.py", line 15, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 508, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/jmoon/.vim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 214, in do_action
[denite]     return action['func'](context)
[denite]   File "/Users/jmoon/.vim/plugged/denite-extra/rplugin/python3/denite/source/history.py", line 78, in action_execute
[denite]     self.vim.call('denite#extra#search', command)
[denite]   File "/Users/jmoon/Library/Python/3.6/lib/python/site-packages/neovim/api/nvim.py", line 230, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/Users/jmoon/Library/Python/3.6/lib/python/site-packages/neovim/api/nvim.py", line 131, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/Users/jmoon/Library/Python/3.6/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(call):E118: Too many arguments for function: function'
[denite] Please execute :messages command.
```

**Comment by chemzqm** [comment]
@sodiumjoe it looks like you neovim doesn't support `Partial` try use `:h Partial` and see what you get. I need to find a way to detect it.

**Comment by Shougo** [comment]
The latest neovim supports the Partial feature.
I think your neovim is old.

**Comment by chemzqm** [comment]
I tried threading in python, but would cause bug of denite.
I've switched to use a source variable to get rid of partial.

**Comment by sodiumjoe** [comment]
I'm still getting the same error after updating `denite-extra`.

on `:h Partial` i get `E149: Sorry, no help for Partial`.

I'm on the most recent release of neovim:

```bash
nvim -v
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170304-65726-1i5z3b3/neovim-0.1.7/build/config -I/tmp/neovim-20170304-65726-1i5z3b3/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170304-65726-1i5z3b3/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170304-65726-1i5z3b3/neovim-0.1.7/build/include
Compiled by jmoon@jmoon

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"

```

**Comment by sodiumjoe** [comment]
@chemzqm ☝️

**Comment by chemzqm** [comment]
@sodiumjoe fixed, I forgot to improve the search function.

**Comment by sodiumjoe** [comment]
fantastic, thank you!
