### ISSUE TITLE
Clash with Denite history:cmd

### ISSUE THREAD

**Issue by petobens** [neoclide/denite-extra#5]
If I run a `:Denite history:cmd` and press enter on one of the candidates I get:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 136, in _start
[denite]     status = self._prompt.start()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 201, in start
[denite]     raise e
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/prompt.py", line 96, in on_keypress
[denite]     ret = self.action.call(self, m.group('action'))
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/action.py", line 18, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 693, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 315, in do_action
[denite]     return action['func'](context) if action['func'] else self._vim.call(
[denite]   File "/Users/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/source/history.py", line 82, in action_execute
[denite]     self.vim.call('denite#util#execute_command', command)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 284, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim:E119: Not enough arguments for function: denite#util#execute_command'
[denite] Please execute :messages command.
```

**Comment by chemzqm** [comment]
Denite has changed the signature of denite#util#execute_command

**Comment by petobens** [comment]
Thanks!
